const listMenuHeader = [
	{
		id: 1,
		name: "Trang chủ",
		path: "/",
	},
	{
		id: 2,
		name: "Giới thiệu",
		path: "/about",
	},
	{
		id: 3,
		name: "Blog",
		path: "/blog",
	},
	{
		id: 4,
		name: "Hoạt động",
		path: "/blog",
	},
	{
		id: 5,
		name: "Dự án",
		path: "/blog",
	},
	{
		id: 6,
		name: "Liên hệ",
		path: "/blog",
	},
];
const ranksLogo = [
	{
		name: "highlight",
		url: "highlight.png",
		width: "182px",
		height: "206px",
		widthImg: "84px",
		heightImg: "84px",
		top: "22%",
		bottom: "63px",
	},
	{
		name: "master",
		url: "master.png",
		width: "182px",
		height: "206px",
		widthImg: "84px",
		heightImg: "84px",
		top: "22%",
		bottom: "63px",
	},
	{
		name: "seo",
		url: "seo.png",
		width: "200px",
		height: "226px",
		widthImg: "86px",
		heightImg: "86px",
		top: "30%",
		bottom: "60px",
	},
	{
		name: "diamond",
		url: "diamond.png",
		width: "200px",
		height: "205px",
		widthImg: "90px",
		heightImg: "90px",
		top: "29%",
		bottom: "48px",
	},
	{
		name: "platinum",
		url: "platinum.png",
		width: "156px",
		height: "160px",
		widthImg: "86px",
		heightImg: "86px",
		top: "23%",
		bottom: "30px",
	},
	{
		name: "gold",
		url: "gold.png",
		width: "115px",
		height: "118px",
		widthImg: "80px",
		heightImg: "80px",
		top: "17%",
		bottom: "30px",
	},
	{
		name: "bronze",
		url: "bronze.png",
		width: "108px",
		height: "111px",
		widthImg: "80px",
		heightImg: "80px",
		top: "15%",
		bottom: "18px",
	},
];
export {listMenuHeader, ranksLogo};
